server:
  port: 8081
  servlet:
    context-path: /dd-mp
# 日志相关
logging:
  level:
    root: DEBUG
    nohi.cxf: DEBUG
  file:
    path: ${HOME}/tmp/logs
  logback:
    rolling-policy:
      # 100MB
      max-file-size: 100
      max-history: 7

# 定义feign相关配置
feign:
  client:
    config:
      default:
        # 设置feign日志级别
        loggerLevel: full
      # 微服务名称
      cont:
        # 设置feign日志级别
        loggerLevel: full
  httpclient:
    enabled: false
  okhttp:
    enabled: true

pagehelper:
  reasonable: true

spring:
  application:
    name: nohi
  jackson:
    default-property-inclusion: non_null
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  aop:
    proxy-target-class: true
  jpa:
    database: mysql
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false
        format_sql: false
        show-sql: false
        enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dingtalk?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: aaaa
    password: bbbb
    driver-class-name: com.mysql.cj.jdbc.Driver

# mp配置
dingtalk:
  mp:
    agentId: xxxxxx
    appKey: aaaaaa
    appSecret: bbbbbb
    dingTalkServer: https://oapi.dingtalk.com
    managerId: ddddd
