package nohi.demo.mp.dt.entity.jpa;

import lombok.Data;
import lombok.EqualsAndHashCode;
import nohi.demo.common.das.OperationTracablePO;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Database Table Remarks:
 * 假期类型
 * <p>
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table DtVocationType
 */
@Data
@EqualsAndHashCode(callSuper = true)
@Entity
@Table(name = "DT_VOCATION_TYPE")
public class DtVocationType extends OperationTracablePO<String> {
    /**
     * 主键
     * DT_VOCATION_TYPE.ID
     */
    @Id
    private String id;

    /**
     * 假期规则唯一标识，同主键ID
     * DT_VOCATION_TYPE.LEAVE_CODE
     */
    @Column(name = "LEAVE_CODE")
    private String leaveCode;

    /**
     * 假期名称
     * DT_VOCATION_TYPE.LEAVE_NAME
     */
    @Column(name = "LEAVE_NAME")
    private String leaveName;

    /**
     * 请假单位：percent_day：表示天；percent_hour：表示小时
     * DT_VOCATION_TYPE.LEAVE_VIEW_UNIT
     */
    @Column(name = "LEAVE_VIEW_UNIT")
    private String leaveViewUnit;

    /**
     * 假期类型。general_leave：普通假期; lieu_leave：加班转调休
     * DT_VOCATION_TYPE.BIZ_TYPE
     */
    @Column(name = "BIZ_TYPE")
    private String bizType;

    /**
     * 是否按照自然日统计请假时长。 true：按照自然日统计请假时长; false：不按照自然日统计请假时长
     * DT_VOCATION_TYPE.NATURAL_DAY_LEAVE
     */
    @Column(name = "NATURAL_DAY_LEAVE")
    private String naturalDayLeave;

    /**
     * 有效类型。absolute_time：绝对时间；relative_time：相对时间
     * DT_VOCATION_TYPE.VALIDITY_TYPE
     */
    @Column(name = "VALIDITY_TYPE")
    private String validityType;

    /**
     * 延长日期。当validity_type为absolute_time该值不为空且满足“yy-mm”格式。当validity_type为relative_time该值为大于1的整数。
     * DT_VOCATION_TYPE.VALIDITY_VALUE
     */
    @Column(name = "VALIDITY_VALUE")
    private String validityValue;

    /**
     * 每天折算的工作时长，百分之一。例如：1天=10小时=1000。
     * DT_VOCATION_TYPE.HOURS_IN_PER_DAY
     */
    @Column(name = "HOURS_IN_PER_DAY")
    private String hoursInPerDay;

    /**
     * 假期来源。external：开放接口自定义的；inner：oa后台新建的
     * DT_VOCATION_TYPE.SOURCE
     */
    @Column(name = "SOURCE")
    private String source;
}
